version: '3'

services:
    brevets:
        build: brevets/.
        command: flask_brevets.py
        ports: 
            - "5001:5000"
        environment:
            MONGODB_HOSTNAME: mongodb
    mongodb:
        image: mongo:latest
        depends_on:
            - brevets